import os
import re
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Tuple


def load_dotenv_if_present(base_dir: Path) -> None:
    env_path = base_dir / ".env"
    if not env_path.exists():
        return
    try:
        for raw_line in env_path.read_text(encoding="utf-8").splitlines():
            line = (raw_line or "").strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = (key or "").strip()
            if not key or key in os.environ:
                continue
            value = (value or "").strip()
            if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
                value = value[1:-1]
            os.environ[key] = value
    except Exception:
        return


def quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def quote_sql_text(value: Any) -> str:
    text = str(value).replace("'", "''")
    return f"'{text}'"


def map_sqlite_type_to_pg(sqlite_type: str) -> str:
    t = (sqlite_type or "").upper()
    if "INT" in t:
        return "BIGINT"
    if any(x in t for x in ["CHAR", "CLOB", "TEXT"]):
        return "TEXT"
    if "BLOB" in t:
        return "BYTEA"
    if any(x in t for x in ["REAL", "FLOA", "DOUB"]):
        return "DOUBLE PRECISION"
    if "BOOL" in t:
        return "BOOLEAN"
    if any(x in t for x in ["DATE", "TIME"]):
        return "TIMESTAMP"
    return "TEXT"


def is_sqlite_auto_pk(col: Dict[str, Any], pk_cols: List[str]) -> bool:
    col_type = (col.get("type") or "").upper()
    return len(pk_cols) == 1 and col.get("name") == pk_cols[0] and "INT" in col_type


def bool_literal(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return "TRUE" if int(value) != 0 else "FALSE"

    text = str(value).strip().strip("'").strip('"').lower()
    if text in {"1", "true", "t", "yes", "y", "on"}:
        return "TRUE"
    if text in {"0", "false", "f", "no", "n", "off", ""}:
        return "FALSE"
    raise ValueError(f"无法转换为 BOOLEAN: {value!r}")


def timestamp_literal(value: Any) -> str:
    if value is None:
        return "NULL"

    if isinstance(value, (int, float)):
        ts = float(value)
        if ts > 1_000_000_000_000:
            ts /= 1000.0
        return f"TO_TIMESTAMP({ts})"

    text = str(value).strip()
    if not text:
        return "NULL"

    if re.fullmatch(r"-?\d+(\.\d+)?", text):
        ts = float(text)
        if ts > 1_000_000_000_000:
            ts /= 1000.0
        return f"TO_TIMESTAMP({ts})"

    return quote_sql_text(text)


def default_literal(default_val: Any, pg_type: str) -> str:
    d = str(default_val).strip()
    d_upper = d.upper()

    if d_upper == "CURRENT_TIMESTAMP":
        return "CURRENT_TIMESTAMP"

    if pg_type == "BOOLEAN":
        return bool_literal(d)

    return d


def build_create_table_sql(table: str, columns: List[Dict[str, Any]], pk_cols: List[str]) -> str:
    defs: List[str] = []
    for col in columns:
        name = col["name"]
        col_type = map_sqlite_type_to_pg(col.get("type") or "")
        default_val = col.get("default")
        not_null = bool(col.get("notnull"))
        if is_sqlite_auto_pk(col, pk_cols):
            defs.append(f"{quote_ident(name)} BIGINT GENERATED BY DEFAULT AS IDENTITY")
            continue

        default_clause = ""
        if default_val is not None:
            default_clause = f" DEFAULT {default_literal(default_val, col_type)}"

        nullable_clause = " NOT NULL" if not_null else ""
        defs.append(f"{quote_ident(name)} {col_type}{default_clause}{nullable_clause}")

    pk_clause = ""
    if pk_cols:
        pk_joined = ", ".join(quote_ident(c) for c in pk_cols)
        pk_clause = f", PRIMARY KEY ({pk_joined})"
    return f"CREATE TABLE IF NOT EXISTS {quote_ident(table)} ({', '.join(defs)}{pk_clause});"


def sql_literal(value: Any, col: Dict[str, Any]) -> str:
    if value is None:
        return "NULL"

    pg_type = map_sqlite_type_to_pg(col.get("type") or "")
    if pg_type == "BOOLEAN":
        return bool_literal(value)
    if pg_type == "TIMESTAMP":
        return timestamp_literal(value)

    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (bytes, bytearray)):
        return "'\\x" + bytes(value).hex() + "'"
    return quote_sql_text(value)


def collect_table_info(cursor, table: str) -> Tuple[List[Dict[str, Any]], List[str]]:
    cursor.execute(f'PRAGMA table_info("{table.replace(chr(34), chr(34) * 2)}")')
    rows = cursor.fetchall()

    columns: List[Dict[str, Any]] = []
    pk_cols: List[Tuple[int, str]] = []
    for r in rows:
        col = {
            "name": r["name"],
            "type": r["type"] or "",
            "notnull": int(r["notnull"]) == 1,
            "default": r["dflt_value"],
            "pk": int(r["pk"]) if r["pk"] is not None else 0,
        }
        columns.append(col)
        if col["pk"] > 0:
            pk_cols.append((col["pk"], col["name"]))
    ordered_pk = [name for _, name in sorted(pk_cols, key=lambda x: x[0])]
    return columns, ordered_pk


def main() -> None:
    base_dir = Path(__file__).resolve().parent
    load_dotenv_if_present(base_dir)

    db_path = Path(os.getenv("DB_PATH", "data/xianyu_data.db"))
    if not db_path.is_absolute():
        db_path = base_dir / db_path
    if not db_path.exists():
        raise SystemExit(f"本地数据库不存在: {db_path}")

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_dir = base_dir / "exports" / f"sqlite_sql_export_{ts}"
    out_dir.mkdir(parents=True, exist_ok=True)
    sql_file = out_dir / "import_to_postgres.sql"

    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    try:
        cur.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )
        tables = [r[0] for r in cur.fetchall()]
        if not tables:
            raise SystemExit("未发现业务表")

        with sql_file.open("w", encoding="utf-8") as f:
            f.write("-- SQLite -> PostgreSQL 导入SQL\n")
            f.write(f"-- Source: {db_path}\n")
            f.write(f"-- Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
            f.write("BEGIN;\n\n")

            total_rows = 0
            for table in tables:
                cols, pk_cols = collect_table_info(cur, table)
                create_sql = build_create_table_sql(table, cols, pk_cols)
                f.write(f"-- table: {table}\n")
                f.write(create_sql + "\n")

                col_names = [c["name"] for c in cols]
                cur.execute(f"SELECT * FROM {quote_ident(table)}")
                rows = cur.fetchall()
                if rows:
                    cols_sql = ", ".join(quote_ident(c) for c in col_names)
                    for row in rows:
                        values_sql = ", ".join(
                            sql_literal(row[col["name"]], col) for col in cols
                        )
                        f.write(f"INSERT INTO {quote_ident(table)} ({cols_sql}) VALUES ({values_sql});\n")
                    total_rows += len(rows)
                f.write("\n")
                print(f"[OK] {table}: {len(rows)} 行")

            f.write("COMMIT;\n")
            f.write(f"-- total rows: {total_rows}\n")

        print(f"\nSQL导出完成: {sql_file}")
    finally:
        try:
            cur.close()
            conn.close()
        except Exception:
            pass


if __name__ == "__main__":
    main()
