import argparse
import os
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import urlparse

import psycopg2
from psycopg2.extras import execute_values


def load_dotenv_if_present(base_dir: Path) -> None:
    env_path = base_dir / ".env"
    if not env_path.exists():
        return
    try:
        for raw_line in env_path.read_text(encoding="utf-8").splitlines():
            line = (raw_line or "").strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = (key or "").strip()
            if not key or key in os.environ:
                continue
            value = (value or "").strip()
            if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
                value = value[1:-1]
            os.environ[key] = value
    except Exception:
        return


def read_primary_database_url() -> str:
    for env_name in ("DATABASE_URL_XIANYU", "DATABASE_URL"):
        value = (os.getenv(env_name) or "").strip()
        if value:
            return value
    return ""


def map_sqlite_type_to_pg(sqlite_type: str) -> str:
    t = (sqlite_type or "").upper()
    if "INT" in t:
        return "BIGINT"
    if any(x in t for x in ["CHAR", "CLOB", "TEXT"]):
        return "TEXT"
    if "BLOB" in t:
        return "BYTEA"
    if any(x in t for x in ["REAL", "FLOA", "DOUB"]):
        return "DOUBLE PRECISION"
    if "BOOL" in t:
        return "BOOLEAN"
    if any(x in t for x in ["DATE", "TIME"]):
        return "TIMESTAMP"
    return "TEXT"


def quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def is_sqlite_auto_pk(col: Dict[str, Any], pk_cols: List[str]) -> bool:
    col_type = (col.get("type") or "").upper()
    return len(pk_cols) == 1 and col.get("name") == pk_cols[0] and "INT" in col_type


def build_create_table_sql(table: str, columns: List[Dict[str, Any]], pk_cols: List[str]) -> str:
    defs: List[str] = []

    for col in columns:
        name = col["name"]
        col_type = map_sqlite_type_to_pg(col.get("type") or "")
        default_val = col.get("default")
        not_null = bool(col.get("notnull"))
        is_auto_pk = is_sqlite_auto_pk(col, pk_cols)

        if is_auto_pk:
            # 对应 SQLite INTEGER PRIMARY KEY AUTOINCREMENT
            defs.append(f"{quote_ident(name)} BIGINT GENERATED BY DEFAULT AS IDENTITY")
            continue

        default_clause = ""
        if default_val is not None:
            d = str(default_val).strip()
            if d.upper() == "CURRENT_TIMESTAMP":
                default_clause = " DEFAULT CURRENT_TIMESTAMP"
            elif d.upper() in {"TRUE", "FALSE"}:
                default_clause = f" DEFAULT {d.upper()}"
            else:
                default_clause = f" DEFAULT {d}"

        nullable_clause = " NOT NULL" if not_null else ""
        defs.append(f"{quote_ident(name)} {col_type}{default_clause}{nullable_clause}")

    pk_clause = ""
    if pk_cols:
        pk_joined = ", ".join(quote_ident(c) for c in pk_cols)
        pk_clause = f", PRIMARY KEY ({pk_joined})"

    return f"CREATE TABLE IF NOT EXISTS {quote_ident(table)} ({', '.join(defs)}{pk_clause});"


def normalize_value_for_pg(col_type: str, value: Any) -> Any:
    if value is None:
        return None

    t = (col_type or "").upper()
    if "BOOL" in t:
        if isinstance(value, (int, float)):
            return bool(value)
        if isinstance(value, str):
            lv = value.strip().lower()
            if lv in {"1", "true", "yes", "on"}:
                return True
            if lv in {"0", "false", "no", "off"}:
                return False
    if any(x in t for x in ["DATE", "TIME"]):
        if isinstance(value, (int, float)):
            try:
                return datetime.fromtimestamp(float(value))
            except Exception:
                return str(value)
    return value


def ensure_table_columns(
    pg_cursor,
    table: str,
    sqlite_columns: List[Dict[str, Any]],
) -> None:
    pg_cursor.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema='public' AND table_name=%s
        """,
        (table,),
    )
    existing_cols = {r[0] for r in pg_cursor.fetchall()}

    for col in sqlite_columns:
        col_name = col["name"]
        if col_name in existing_cols:
            continue
        col_type = map_sqlite_type_to_pg(col.get("type") or "")
        sql = (
            f"ALTER TABLE {quote_ident(table)} "
            f"ADD COLUMN IF NOT EXISTS {quote_ident(col_name)} {col_type}"
        )
        pg_cursor.execute(sql)


def sync_identity_sequence(pg_cursor, table: str, pk_cols: List[str]) -> None:
    if len(pk_cols) != 1:
        return
    pk_col = pk_cols[0]
    seq_sql = f"SELECT pg_get_serial_sequence('{table}', '{pk_col}')"
    pg_cursor.execute(seq_sql)
    seq = pg_cursor.fetchone()
    if not seq or not seq[0]:
        return
    seq_name = seq[0]
    reset_sql = (
        f"SELECT setval('{seq_name}', "
        f"COALESCE((SELECT MAX({quote_ident(pk_col)}) FROM {quote_ident(table)}), 1), true)"
    )
    pg_cursor.execute(reset_sql)


def collect_sqlite_table_info(sqlite_cursor, table: str) -> Tuple[List[Dict[str, Any]], List[str]]:
    sqlite_cursor.execute(f"PRAGMA table_info({table})")
    rows = sqlite_cursor.fetchall()

    columns: List[Dict[str, Any]] = []
    pk_cols: List[Tuple[int, str]] = []
    for r in rows:
        col = {
            "name": r["name"],
            "type": r["type"] or "",
            "notnull": int(r["notnull"]) == 1,
            "default": r["dflt_value"],
            "pk": int(r["pk"]) if r["pk"] is not None else 0,
        }
        columns.append(col)
        if col["pk"] > 0:
            pk_cols.append((col["pk"], col["name"]))

    ordered_pk_cols = [name for _, name in sorted(pk_cols, key=lambda x: x[0])]
    return columns, ordered_pk_cols


def table_row_count(cursor, table: str, sqlite_mode: bool) -> int:
    if sqlite_mode:
        cursor.execute(f"SELECT COUNT(*) FROM {table}")
    else:
        cursor.execute(f"SELECT COUNT(*) FROM {quote_ident(table)}")
    return int(cursor.fetchone()[0])


def migrate(
    sqlite_db_path: Path,
    pg_url: str,
    truncate_before_insert: bool,
    schema_only: bool,
    page_size: int = 1000,
) -> None:
    if not sqlite_db_path.exists():
        raise SystemExit(f"本地数据库不存在: {sqlite_db_path}")

    sq = sqlite3.connect(str(sqlite_db_path))
    sq.row_factory = sqlite3.Row
    s = sq.cursor()

    pg = psycopg2.connect(pg_url, connect_timeout=10)
    p = pg.cursor()

    try:
        s.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
        tables = [r[0] for r in s.fetchall()]
        print(f"发现 SQLite 表: {len(tables)}")

        migrated_count = 0
        for table in tables:
            cols, pk_cols = collect_sqlite_table_info(s, table)
            if not cols:
                continue

            create_sql = build_create_table_sql(table, cols, pk_cols)
            p.execute(create_sql)
            ensure_table_columns(p, table, cols)
            pg.commit()

            if schema_only:
                migrated_count += 1
                print(f"[OK] {table}: schema-only")
                continue

            col_names = [c["name"] for c in cols]
            sqlite_select = ", ".join(col_names)
            pg_col_list = ", ".join(quote_ident(c) for c in col_names)

            s.execute(f"SELECT {sqlite_select} FROM {table}")
            src_rows = s.fetchall()

            if truncate_before_insert:
                p.execute(f"TRUNCATE TABLE {quote_ident(table)} RESTART IDENTITY CASCADE")

            if src_rows:
                values: List[Tuple[Any, ...]] = []
                for row in src_rows:
                    row_vals = tuple(
                        normalize_value_for_pg(col.get("type") or "", row[col["name"]])
                        for col in cols
                    )
                    values.append(row_vals)
                insert_sql = f"INSERT INTO {quote_ident(table)} ({pg_col_list}) VALUES %s"
                execute_values(p, insert_sql, values, page_size=page_size)

            sync_identity_sequence(p, table, pk_cols)
            pg.commit()

            src_count = len(src_rows)
            dst_count = table_row_count(p, table, sqlite_mode=False)
            print(f"[OK] {table}: SQLite={src_count}, PostgreSQL={dst_count}")
            migrated_count += 1

        print(f"迁移完成，处理表数量: {migrated_count}")
    finally:
        try:
            p.close()
            pg.close()
        except Exception:
            pass
        sq.close()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="将 SQLite 数据库全量迁移到 PostgreSQL")
    parser.add_argument(
        "--sqlite-db",
        default=os.getenv("DB_PATH", "data/xianyu_data.db"),
        help="SQLite 数据库路径，默认读取 DB_PATH 或 data/xianyu_data.db",
    )
    parser.add_argument(
        "--pg-url",
        default=read_primary_database_url(),
        help="PostgreSQL 连接串，默认读取 DATABASE_URL_XIANYU 或兼容变量 DATABASE_URL",
    )
    parser.add_argument(
        "--truncate",
        action="store_true",
        help="导入前清空远程对应表（TRUNCATE ... CASCADE）",
    )
    parser.add_argument(
        "--schema-only",
        action="store_true",
        help="仅创建/补齐表结构，不导入数据",
    )
    parser.add_argument(
        "--page-size",
        type=int,
        default=1000,
        help="批量插入每批大小，默认 1000",
    )
    return parser.parse_args()


def validate_pg_url(pg_url: str) -> None:
    if not pg_url:
        raise SystemExit(
            "缺少 PostgreSQL 连接串，请在 .env 设置 DATABASE_URL_XIANYU "
            "或兼容变量 DATABASE_URL，或通过 --pg-url 传入"
        )
    parsed = urlparse(pg_url)
    if parsed.scheme not in {"postgresql", "postgres"}:
        raise SystemExit(f"PostgreSQL 连接串协议不正确: {parsed.scheme}")


if __name__ == "__main__":
    base_dir = Path(__file__).resolve().parent
    load_dotenv_if_present(base_dir)

    args = parse_args()
    sqlite_db = Path(args.sqlite_db)
    pg_url = (args.pg_url or "").strip()
    validate_pg_url(pg_url)

    print(f"SQLite: {sqlite_db}")
    print(f"PostgreSQL: {pg_url.split('@')[-1] if '@' in pg_url else pg_url}")
    if args.schema_only:
        print("模式: 仅建表/补齐字段（不导入数据）")
    else:
        print(f"模式: {'覆盖远端(先TRUNCATE)' if args.truncate else '追加导入(不清空)'}")

    migrate(
        sqlite_db,
        pg_url,
        truncate_before_insert=(args.truncate and (not args.schema_only)),
        schema_only=bool(args.schema_only),
        page_size=max(1, args.page_size),
    )
